In [49]:
#importing the relevant libraries
import pandas as pd
import numpy as np
import os
from glob import glob
import sys
pd.set_option('display.max_columns', None, 'display.max_rows', None)

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
# pd.set_option('max_colwidth',-1)

In [50]:
#Collecting and concatenating all csv files per year
# path_folder = "./sampledata/"
# folder_list = os.listdir("./sampledata")
# EXT = "*.csv"
# print(folder_list)
# for sub in folder_list[:1]:
#     print(sub)
#     PATH = path_folder + sub
#     print(PATH)
#     all_csv_files = [file 
#                      for path, subdir, files in os.walk(PATH)
#                      for file in glob(os.path.join(path,EXT))
#                     ]
#     #print(all_csv_files)
#     df = pd.concat((pd.read_csv(f, sep=";", encoding = "ISO-8859-1").assign(file_loc=f) for f in all_csv_files))

#     df = df.rename(columns=lambda x: x.strip())
#     df.to_csv('./cleaned/' + sub + '.csv', index = False)

In [59]:
#Concatenating datasets cross the years
data_14 = pd.read_csv('./cleaned/2014-2015.CSV')
data_15 = pd.read_csv('./cleaned/2015-2016.CSV')
data_16 = pd.read_csv('./cleaned/2016-2017.CSV')
data_17 = pd.read_csv('./cleaned/2017-2018.CSV')
data_18 = pd.read_csv('./cleaned/2018-2019.CSV')
data_test = pd.read_csv('./cleaned/Test.CSV')

col14 = data_14.columns
col15 = data_15.columns
col16 = data_16.columns
col17 = data_17.columns
col18 = data_18.columns
test_d = data_test.columns
all_cols = list(set(col14) | set(col15) | set(col16) |set(col17) |set(col18) |set(test_d))
common_cols = list(set(col14) & set(col15) & set(col16) & set(col17) & set(col18) & set(test_d))
all_contest_data = ['./cleaned/2014-2015.CSV','./cleaned/2015-2016.CSV','./cleaned/2016-2017.CSV',
                    './cleaned/2017-2018.CSV','./cleaned/2018-2019.CSV','./cleaned/Test.CSV']
df = pd.concat(pd.read_csv(f)[common_cols] for f in all_contest_data)
df.columns
df.shape
df.describe()

Index(['Unnamed: 25', 'S3_LARGE', 'S2_IMPROVEMENT', 'DRIVER_NUMBER',
       'PIT_TIME', 'LAP_NUMBER', 'DRIVER_SECONDNAME', 'FL_KPH', 'S1_LARGE',
       'ï»¿POSITION', 'KPH', 'NUMBER', 'S1_IMPROVEMENT',
       'CROSSING_FINISH_LINE_IN_PIT', 'DRIVER_FIRSTNAME', 'DRIVER_COUNTRY',
       'S1', 'S2', 'LAP_IMPROVEMENT', 'FL_LAPNUM', 'GAP_FIRST', 'S2_LARGE',
       'DRIVER_LICENSE', 'MANUFACTURER', 'FL_TIME', 'TOP_SPEED', 'CLASS', 'S3',
       'DRIVER_SHORTNAME', 'GAP_PREVIOUS', 'LAPS', 'HOUR', 'file_loc',
       'ï»¿NUMBER', 'ELAPSED', 'VEHICLE', 'GROUP', 'TEAM', 'TOTAL_TIME',
       'DIVISION', 'DRIVER_HOMETOWN', 'TIRES', 'S3_IMPROVEMENT', 'DRIVER_NAME',
       'LAP_TIME', 'STATUS'],
      dtype='object')

(74012, 46)

,Unnamed: 25,S2_IMPROVEMENT,DRIVER_NUMBER,LAP_NUMBER,FL_KPH,ï»¿POSITION,KPH,NUMBER,S1_IMPROVEMENT,LAP_IMPROVEMENT,FL_LAPNUM,DRIVER_LICENSE,TOP_SPEED,CLASS,DRIVER_SHORTNAME,LAPS,ï»¿NUMBER,DIVISION,TIRES,S3_IMPROVEMENT
count,0.0,73792.000000,73792.000000,73792.000000,217.000000,181.000000,67388.000000,220.000000,73792.000000,73792.000000,220.000000,0.0,0.0,0.0,0.0,220.000000,73792.000000,0.0,0.0,73792.000000
mean,NaN,0.112343,0.086784,14.656467,116.272350,8.823204,101.683755,29.650000,0.110432,0.113020,23.259091,NaN,NaN,NaN,NaN,30.704545,24.287118,NaN,NaN,0.113454
std,NaN,0.479707,0.281521,10.927544,6.986659,4.913893,25.887216,29.621204,0.476026,0.481071,8.467028,NaN,NaN,NaN,NaN,8.970727,24.259728,NaN,NaN,0.481729
min,NaN,0.000000,0.000000,0.000000,102.100000,1.000000,1.700000,2.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,0.000000,1.000000,NaN,NaN,0.000000
25%,NaN,0.000000,0.000000,6.000000,112.700000,5.000000,100.200000,7.750000,0.000000,0.000000,20.000000,NaN,NaN,NaN,NaN,29.000000,7.000000,NaN,NaN,0.000000
50%,NaN,0.000000,0.000000,12.000000,115.800000,9.000000,109.400000,19.500000,0.000000,0.000000,25.000000,NaN,NaN,NaN,NaN,31.000000,19.000000,NaN,NaN,0.000000
75%,NaN,0.000000,0.000000,21.000000,119.900000,13.000000,116.000000,36.250000,0.000000,0.000000,29.000000,NaN,NaN,NaN,NaN,35.000000,28.000000,NaN,NaN,0.000000
max,NaN,4.000000,1.000000,51.000000,130.100000,19.000000,184.500000,99.000000,4.000000,4.000000,47.000000,NaN,NaN,NaN,NaN,47.000000,99.000000,NaN,NaN,4.000000

In [60]:
df["Test_or_not"] = 0
df['Test_or_not'][72725:] = 1
df['Test_or_not'].tail()

<ipython-input-60-2ae0d0a91c0a>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Test_or_not'][72725:] = 1

1282    1
1283    1
1284    1
1285    1
1286    1
Name: Test_or_not, dtype: int64

In [61]:
df.columns

Index(['Unnamed: 25', 'S3_LARGE', 'S2_IMPROVEMENT', 'DRIVER_NUMBER',
       'PIT_TIME', 'LAP_NUMBER', 'DRIVER_SECONDNAME', 'FL_KPH', 'S1_LARGE',
       'ï»¿POSITION', 'KPH', 'NUMBER', 'S1_IMPROVEMENT',
       'CROSSING_FINISH_LINE_IN_PIT', 'DRIVER_FIRSTNAME', 'DRIVER_COUNTRY',
       'S1', 'S2', 'LAP_IMPROVEMENT', 'FL_LAPNUM', 'GAP_FIRST', 'S2_LARGE',
       'DRIVER_LICENSE', 'MANUFACTURER', 'FL_TIME', 'TOP_SPEED', 'CLASS', 'S3',
       'DRIVER_SHORTNAME', 'GAP_PREVIOUS', 'LAPS', 'HOUR', 'file_loc',
       'ï»¿NUMBER', 'ELAPSED', 'VEHICLE', 'GROUP', 'TEAM', 'TOTAL_TIME',
       'DIVISION', 'DRIVER_HOMETOWN', 'TIRES', 'S3_IMPROVEMENT', 'DRIVER_NAME',
       'LAP_TIME', 'STATUS', 'Test_or_not'],
      dtype='object')

In [62]:
df.to_csv('./cleaned/contest_data.csv', index = False)

In [40]:
data_wheather = pd.read_csv('./cleaned/wheather.CSV',decimal=",")
data_wheather['DATE_ONLY'] = pd.to_datetime(data_wheather['TIME_UTC_STR']).dt.strftime('%m/%d/%Y')
data_wheather = data_wheather.sort_values(by=['DATE_ONLY']).drop(columns=["Unnamed: 8"])

data_wheather = data_wheather.assign(season_year = lambda x: x['file_loc'].str.split('\\').str[1])\
                .assign(location = lambda x: x['file_loc'].str.split('\\').str[2])\
                .assign(match_type = lambda x: x['file_loc'].str.split('\\').str[3])\
                .assign(match_name = lambda x: x['file_loc'].str.split('\\').str[4])\
                .assign(match_name = lambda x: x['match_name'].str.split('_').str[2])\
                .assign(match_name = lambda x: x['match_name'].str.split('.').str[0])\
                .drop(columns = ['file_loc'])

In [41]:
aggregation = {'AIR_TEMP':[('mean_air_temp','mean'),
                ('std_air_temp','std'),
                ('med_air_temp','median'),
                ('max_air_temp','max'),
                ('min_air_temp','min'),
                ('range_air_temp',lambda x: max(x) - min(x)),
                ('skew_air_temp','skew')],
              'TRACK_TEMP' : [('mean_track_temp','mean'),
                ('std_track_temp','std'),
                ('med_track_temp','median'),
                ('max_track_temp','max'),
                ('min_track_temp','min'),
                ('range_track_temp',lambda x: max(x) - min(x)),
                ('skew_track_temp','skew')],
                'HUMIDITY' : [('mean_HUMIDITY','mean'),
                            ('std_HUMIDITY','std'),
                            ('med_HUMIDITY','median'),
                            ('max_HUMIDITY','max'),
                            ('min_HUMIDITY','min'),
                            ('range_HUMIDITY',lambda x: max(x) - min(x)),
                            ('skew_HUMIDITY','skew')],
                'PRESSURE' : [('mean_PRESSURE','mean'),
                    ('std_PRESSURE','std'),
                    ('med_PRESSURE','median'),
                    ('max_PRESSURE','max'),
                    ('min_PRESSURE','min'),
                    ('range_PRESSURE',lambda x: max(x) - min(x)),
                    ('skew_PRESSURE','skew')],

            'WIND_SPEED' : [('mean_WIND_SPEED','mean'),
                          ('std_WIND_SPEED','std'),
                          ('med_WIND_SPEED','median'),
                          ('max_WIND_SPEED','max'),
                          ('min_WIND_SPEED','min'),
                          ('range_WIND_SPEED',lambda x: max(x) - min(x)),
                          ('skew_WIND_SPEED','skew'),
                        ]
              }

#data_wheather[aggregation.keys] = data_wheather[aggregation.keys()].apply(pd.to_numeric)

data_wheather['match_key'] = data_wheather['DATE_ONLY'] + data_wheather['match_name']
df = data_wheather.groupby(['match_key','DATE_ONLY','location','season_year','match_name','match_type'], as_index=True).agg(aggregation).reset_index()
df.columns = df.columns.droplevel()
column_names = df.columns.values
column_names[:6] = ['match_key','DATE_ONLY','location','season_year','match_name','match_type']
df.columns = column_names
df = df.drop(columns = ['match_key'])
df.to_csv('./cleaned/weather_processed.csv',index = False)

In [43]:
df.head()

,DATE_ONLY,location,season_year,match_name,match_type,mean_air_temp,std_air_temp,med_air_temp,max_air_temp,min_air_temp,range_air_temp,skew_air_temp,mean_track_temp,std_track_temp,med_track_temp,max_track_temp,min_track_temp,range_track_temp,skew_track_temp,mean_HUMIDITY,std_HUMIDITY,med_HUMIDITY,max_HUMIDITY,min_HUMIDITY,range_HUMIDITY,skew_HUMIDITY,mean_PRESSURE,std_PRESSURE,med_PRESSURE,max_PRESSURE,min_PRESSURE,range_PRESSURE,skew_PRESSURE,mean_WIND_SPEED,std_WIND_SPEED,med_WIND_SPEED,max_WIND_SPEED,min_WIND_SPEED,range_WIND_SPEED,skew_WIND_SPEED
0,01/04/2017,Mexico,2016-2017,Groups Qualifying Session,Q,27.101836,0.574968,27.4444,27.7222,26.3889,1.3333,-0.406788,21.574100,0.209570,21.6667,21.6667,21.1111,0.5556,-1.855802,31.142857,0.354169,31.0,32,31,1,2.117634,779.436476,0.198200,779.4985,779.719,779.143,0.576,-0.184513,7.165413,1.516478,8.04672,8.04672,3.21869,4.82803,-1.417020
1,01/04/2017,Mexico,2016-2017,Non Qualifying Practice 1,FP1,16.888880,1.024915,17.3333,19.2222,15.0556,4.1666,-0.614885,21.913584,0.816790,21.6667,23.3333,20.5556,2.7777,0.158910,55.155556,0.366529,55.0,56,55,1,1.966912,780.824667,0.061080,780.8020,780.938,780.734,0.204,0.158626,2.610713,1.690992,3.21869,4.82803,0.00000,4.82803,-0.154161
2,01/04/2017,Mexico,2016-2017,Non Qualifying Practice 2,FP2,25.546313,0.219368,25.6667,25.7778,25.1667,0.6111,-0.918498,20.555600,0.000000,20.5556,20.5556,20.5556,0.0000,0.000000,33.266667,0.449776,33.0,34,33,1,1.111663,780.391367,0.062756,780.3960,780.531,780.260,0.271,0.475190,5.954573,2.902056,6.43738,14.48410,1.60934,12.87476,0.898993
3,01/04/2017,Mexico,2016-2017,Race,Race,27.262177,0.175923,27.2778,27.5000,26.9444,0.5556,-0.645954,23.245589,0.204359,23.3333,23.3333,22.7778,0.5555,-1.927487,34.368421,0.486664,34.0,35,34,1,0.560401,777.901351,0.120517,777.8900,778.229,777.687,0.542,0.643746,7.482039,3.310649,6.43738,19.31210,3.21869,16.09341,1.271079
4,01/04/2017,Mexico,2016-2017,Super Pole Session,Q,27.817464,0.145223,27.8889,27.9444,27.5556,0.3888,-1.383638,22.222200,0.000000,22.2222,22.2222,22.2222,0.0000,0.000000,30.642857,0.497245,31.0,31,30,1,-0.670360,778.876857,0.060905,778.8890,778.974,778.770,0.204,-0.435894,6.782234,3.167426,6.43738,16.09340,3.21869,12.87471,1.983345

In [102]:
data_race = pd.read_csv('./cleaned/contest_data.CSV')
data_race = data_race.assign(season_year = lambda x: x['file_loc'].str.split('\\').str[0])\
            .assign(location = lambda x: x['file_loc'].str.split('\\').str[1])\
                .assign(match_type = lambda x: x['file_loc'].str.split('\\').str[2])\
                    .assign(match_name = lambda x: x['file_loc'].str.split('\\').str[3])\
                        .assign(match_name = lambda x: x['match_name'].str.split('_').str[2])\
                            .assign(match_name = lambda x: x['match_name'].str.split('.').str[0])\
                                .assign(match_name = lambda x: x['match_name'].str.replace(r"\(.*\)",""))\
                                    .drop(columns = ['file_loc'])
data_race.to_csv('./cleaned/contest_pre-final.csv',index = False)

/opt/miniconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3071: DtypeWarning: Columns (6,14,15,20,23,24,29,35,36,38,40,45) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [103]:
data_race.head()

,Unnamed: 25,S3_LARGE,S2_IMPROVEMENT,DRIVER_NUMBER,PIT_TIME,LAP_NUMBER,DRIVER_SECONDNAME,FL_KPH,S1_LARGE,ï»¿POSITION,KPH,NUMBER,S1_IMPROVEMENT,CROSSING_FINISH_LINE_IN_PIT,DRIVER_FIRSTNAME,DRIVER_COUNTRY,S1,S2,LAP_IMPROVEMENT,FL_LAPNUM,GAP_FIRST,S2_LARGE,DRIVER_LICENSE,MANUFACTURER,FL_TIME,TOP_SPEED,CLASS,S3,DRIVER_SHORTNAME,GAP_PREVIOUS,LAPS,HOUR,ï»¿NUMBER,ELAPSED,VEHICLE,GROUP,TEAM,TOTAL_TIME,DIVISION,DRIVER_HOMETOWN,TIRES,S3_IMPROVEMENT,DRIVER_NAME,LAP_TIME,STATUS,Test_or_not,season_year,location,match_type,match_name
0,NaN,0:45.392,0.0,0.0,0:01:11.928,1.0,NaN,NaN,1:49.797,NaN,63.0,NaN,0.0,NaN,NaN,NaN,1:49.797,42.184,0.0,NaN,NaN,0:42.184,NaN,NaN,NaN,NaN,NaN,45.392,NaN,NaN,NaN,08:18,10.0,3:17.373,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,Jarno Trulli,3:17.373,NaN,0,./sampledata/2014-2015,Bejing,FP1,Non Qualifying Practice 1
1,NaN,0:39.179,0.0,0.0,NaN,2.0,NaN,NaN,0:42.246,NaN,101.9,NaN,0.0,NaN,NaN,NaN,42.246,40.511,0.0,NaN,NaN,0:40.511,NaN,NaN,NaN,NaN,NaN,39.179,NaN,NaN,NaN,08:20,10.0,5:19.309,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,Jarno Trulli,2:01.936,NaN,0,./sampledata/2014-2015,Bejing,FP1,Non Qualifying Practice 1
2,NaN,0:38.639,0.0,0.0,NaN,3.0,NaN,NaN,0:41.745,NaN,103.4,NaN,0.0,NaN,NaN,NaN,41.745,39.791,0.0,NaN,NaN,0:39.791,NaN,NaN,NaN,NaN,NaN,38.639,NaN,NaN,NaN,08:22,10.0,7:19.484,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,Jarno Trulli,2:00.175,NaN,0,./sampledata/2014-2015,Bejing,FP1,Non Qualifying Practice 1
3,NaN,0:38.205,0.0,0.0,NaN,4.0,NaN,NaN,0:43.439,NaN,102.9,NaN,0.0,NaN,NaN,NaN,43.439,39.186,0.0,NaN,NaN,0:39.186,NaN,NaN,NaN,NaN,NaN,38.205,NaN,NaN,NaN,08:24,10.0,9:20.314,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,Jarno Trulli,2:00.830,NaN,0,./sampledata/2014-2015,Bejing,FP1,Non Qualifying Practice 1
4,NaN,0:37.710,0.0,0.0,NaN,5.0,NaN,NaN,0:41.645,NaN,106.3,NaN,0.0,NaN,NaN,NaN,41.645,37.618,0.0,NaN,NaN,0:37.618,NaN,NaN,NaN,NaN,NaN,37.710,NaN,NaN,NaN,08:26,10.0,11:17.287,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,Jarno Trulli,1:56.973,NaN,0,./sampledata/2014-2015,Bejing,FP1,Non Qualifying Practice 1

In [104]:
data_race = data_race.drop(columns = ['DRIVER_NUMBER', 'LAPS', 'FL_KPH', 'HOUR', 'MANUFACTURER', 'TOTAL_TIME',
       'Unnamed: 25', 'NUMBER', 'DRIVER_SHORTNAME', 'S2_LARGE',
       'FL_LAPNUM', 'VEHICLE',
       'LAP_IMPROVEMENT', 'CLASS', 'S2_IMPROVEMENT', 'TOP_SPEED',
       'DRIVER_COUNTRY', 'STATUS', 'ELAPSED', 'ï»¿POSITION', 'TIRES',
       'S3_LARGE', 'GAP_PREVIOUS', 'ï»¿NUMBER',
       'GAP_FIRST', 'DIVISION', 'DRIVER_SECONDNAME', 'DRIVER_FIRSTNAME',
       'LAP_TIME', 'S1_IMPROVEMENT', 'DRIVER_HOMETOWN', 'FL_TIME',
       'S1_LARGE', 'DRIVER_LICENSE', 'S3_IMPROVEMENT', 'season_year'])
data_race.keys()

Index(['PIT_TIME', 'LAP_NUMBER', 'KPH', 'CROSSING_FINISH_LINE_IN_PIT', 'S1',
       'S2', 'S3', 'GROUP', 'TEAM', 'DRIVER_NAME', 'Test_or_not', 'location',
       'match_type', 'match_name'],
      dtype='object')

In [105]:
data_race.shape

(74012, 14)

In [106]:
import math

for i in (['S1', 'S2', 'S3', 'PIT_TIME']):
    p = data_race[i]
    for count, i in enumerate(p):
        x = len(str(i).split(':'))
        if (pd.isna(i)):
            p[count] = "00:00:00"
        elif (x == 1):
            p[count] = "00:00:" + str(i)
        elif (x == 2):
            p[count] = "00:" + str(i)
        elif (x == 3):
            p[count] = "" + str(i)
        p[count] = float(p[count].split(":")[0])*3600000 + float(p[count].split(":")[1])*60000 + float(p[count].split(":")[2])*1000
    data_race[i] = p
    
data_race[['KPH', 'S1', 'S2', 'S3', 'LAP_NUMBER', 'PIT_TIME']] = data_race[['KPH', 'S1', 'S2', 'S3', 'LAP_NUMBER', 'PIT_TIME']].apply(pd.to_numeric)

<ipython-input-106-98260ef02cbd>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  p[count] = "00:" + str(i)
<ipython-input-106-98260ef02cbd>:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  p[count] = float(p[count].split(":")[0])*3600000 + float(p[count].split(":")[1])*60000 + float(p[count].split(":")[2])*1000
<ipython-input-106-98260ef02cbd>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  p[count] = "00:00:" + str(i)
<ipython-input-106-98260ef02cbd>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  p[count] = "00:00:00"
<ipython-input-106-98260ef02cbd>:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  p[count] = "" + str(i)

In [111]:
data_race.shape

(74012, 18)

In [112]:
df_train = data_race[data_race['Test_or_not'] == 0]
df_train.shape

(72725, 18)

In [113]:
df_test = data_race[data_race['Test_or_not'] == 1]
df_test.shape

(1287, 18)

In [135]:
df_train.columns

Index([                   'PIT_TIME',                  'LAP_NUMBER',
                               'KPH', 'CROSSING_FINISH_LINE_IN_PIT',
                                'S1',                          'S2',
                                'S3',                       'GROUP',
                              'TEAM',                 'DRIVER_NAME',
                       'Test_or_not',                    'location',
                        'match_type',                  'match_name',
                            '39.473',                      '36.775',
                            '40.215',                           nan],
      dtype='object')

In [129]:
#saving the data
df_train_nonag = df_train
df_test_nonag = df_test

In [151]:
df_train = df_train.iloc[:,:14]
df_test = df_test.iloc[:,:14]

In [152]:
#removing columns for proper groupby:
df_train.drop(columns=['Test_or_not', 'GROUP'], inplace=True)
df_test.drop(columns=['Test_or_not', 'GROUP'], inplace=True)

In [159]:
df_test = df_test.reset_index(drop=True)  #df_test.drop(columns=['index'], inplace=True)
df_test.head()

,PIT_TIME,LAP_NUMBER,KPH,CROSSING_FINISH_LINE_IN_PIT,S1,S2,S3,GROUP,TEAM,DRIVER_NAME,location,match_type,match_name
0,12256.0,1.0,80.5,NaN,40055.0,20461.0,18419.0,NaN,ABT Schaeffler Audi Sport,Lucas DI GRASSI,Bejing,FP1,Non Qualifying Practice 1
1,0.0,2.0,104.0,NaN,23287.0,19299.0,18493.0,NaN,ABT Schaeffler Audi Sport,Lucas DI GRASSI,Bejing,FP1,Non Qualifying Practice 1
2,0.0,3.0,111.8,NaN,21710.0,18042.0,17062.0,NaN,ABT Schaeffler Audi Sport,Lucas DI GRASSI,Bejing,FP1,Non Qualifying Practice 1
3,0.0,4.0,41.3,B,21740.0,18370.0,113627.0,NaN,ABT Schaeffler Audi Sport,Lucas DI GRASSI,Bejing,FP1,Non Qualifying Practice 1
4,106166.0,5.0,103.8,NaN,25355.0,18688.0,17200.0,NaN,ABT Schaeffler Audi Sport,Lucas DI GRASSI,Bejing,FP1,Non Qualifying Practice 1

In [173]:
#Train Aggregation
aggregation = {'KPH':[('mean_KPH','mean'),
                ('std_KPH','std'),
                ('med_KPH','median'),
                ('max_KPH','max'),
                ('min_KPH','min'),
                ('range_KPH',lambda x: max(x) - min(x)),
                ('skew_KPH','skew')],
              'S1' : [('mean_S1','mean'),
                ('std_S1','std'),
                ('med_S1','median'),
                ('max_S1','max'),
                ('min_S1','min'),
                ('range_S1',lambda x: max(x) - min(x)),
                ('skew_S1','skew')],
              'S2' : [('mean_S2','mean'),
                ('std_S2','std'),
                ('med_S2','median'),
                ('max_S2','max'),
                ('min_S2','min'),
                ('range_S2',lambda x: max(x) - min(x)),
                ('skew_S2','skew')],
              'S3' : [('mean_S3','mean'),
                ('std_S3','std'),
                ('med_S3','median'),
                ('max_S3','max'),
                ('min_S3','min'),
                ('range_S3',lambda x: max(x) - min(x)),
                ('skew_S3','skew')],
               'LAP_NUMBER': [('Total_Lap_Num','max')],
               'PIT_TIME': [('PIT_TIME_cnt','count')],
               'CROSSING_FINISH_LINE_IN_PIT': [('cnt_CROSSING_FINISH_LINE_IN_PIT','count')],
              }

df_train['match_key'] = df_train['DRIVER_NAME'] + df_train['location'] + df_train['match_type'] + df_train['match_name'] 
dftrain = df_train.groupby(['match_key','DRIVER_NAME','location','match_name','match_type','TEAM'], as_index=True).agg(aggregation).reset_index()
dftrain.columns = dftrain.columns.droplevel()
column_names = dftrain.columns.values
column_names[:6] = ['match_key','DRIVER_NAME','location','match_name','match_type','TEAM']
dftrain.columns = column_names
dftrain = dftrain.drop(columns = ['match_key'])
dftrain = dftrain.fillna(0)
#df.to_csv('./cleaned/race_final_processed.csv',index = False) #this contains test + train

In [176]:
dftrain.shape

(3663, 36)

In [177]:
dftrain.head()

,DRIVER_NAME,location,match_name,match_type,TEAM,mean_KPH,std_KPH,med_KPH,max_KPH,min_KPH,range_KPH,skew_KPH,mean_S1,std_S1,med_S1,max_S1,min_S1,range_S1,skew_S1,mean_S2,std_S2,med_S2,max_S2,min_S2,range_S2,skew_S2,mean_S3,std_S3,med_S3,max_S3,min_S3,range_S3,skew_S3,Total_Lap_Num,PIT_TIME_cnt,cnt_CROSSING_FINISH_LINE_IN_PIT
0,MA Qing Hua,Buenos,Non Qualifying Practice 1,FP1,TECHEETAH,103.200000,27.378660,114.20,123.5,14.2,109.3,-2.195524,4.994981e+04,1.188700e+05,19547.0,563980.0,18318.0,545662.0,4.454455,28510.000000,6829.875314,26398.0,57094.0,24626.0,32468.0,4.006459,34029.952381,6735.738664,31021.0,57394.0,29177.0,28217.0,2.434997,21.0,21,2
1,MA Qing Hua,Buenos,Non Qualifying Practice 2,FP2,TECHEETAH,109.641176,28.468537,118.50,127.0,9.7,117.3,-3.125489,7.058582e+04,2.022678e+05,19025.0,854684.0,17786.0,836898.0,4.108922,26316.941176,2153.207563,25352.0,31165.0,24019.0,7146.0,1.225031,30665.647059,2208.828279,29164.0,34727.0,28266.0,6461.0,0.675108,17.0,17,2
2,MA Qing Hua,Buenos,Groups Qualifying Session,Q,TECHEETAH,55.950000,74.034080,55.95,108.3,3.6,104.7,0.000000,1.205626e+06,1.673677e+06,1205626.5,2389095.0,22158.0,2366937.0,0.000000,28569.500000,2348.301620,28569.5,30230.0,26909.0,3321.0,0.000000,33244.500000,132.228968,33244.5,33338.0,33151.0,187.0,0.000000,2.0,2,0
3,MA Qing Hua,Buenos,Race,Race,TECHEETAH,118.713889,12.634514,121.95,139.3,68.7,70.6,-3.401031,2.122811e+04,1.173587e+04,19022.0,75004.0,0.0,75004.0,3.633619,24864.555556,4687.115881,25011.0,36383.0,0.0,36383.0,-4.056665,29789.361111,2138.332570,29104.5,40848.0,28621.0,12227.0,4.284716,36.0,36,1
4,MA Qing Hua,HongKong,Non Qualifying Practice 2,FP2,TECHEETAH,87.876471,22.896111,98.50,106.0,10.6,95.4,-2.593471,2.156253e+04,5.257301e+03,19077.0,39047.0,17996.0,21051.0,2.601783,23534.705882,3624.731986,22177.0,31945.0,20085.0,11860.0,0.947949,61198.882353,137072.662466,27148.0,593006.0,24874.0,568132.0,4.120136,17.0,17,1

In [178]:
#Test Aggregation
aggregation = {'KPH':[('mean_KPH','mean'),
                ('std_KPH','std'),
                ('med_KPH','median'),
                ('max_KPH','max'),
                ('min_KPH','min'),
                ('range_KPH',lambda x: max(x) - min(x)),
                ('skew_KPH','skew')],
              'S1' : [('mean_S1','mean'),
                ('std_S1','std'),
                ('med_S1','median'),
                ('max_S1','max'),
                ('min_S1','min'),
                ('range_S1',lambda x: max(x) - min(x)),
                ('skew_S1','skew')],
              'S2' : [('mean_S2','mean'),
                ('std_S2','std'),
                ('med_S2','median'),
                ('max_S2','max'),
                ('min_S2','min'),
                ('range_S2',lambda x: max(x) - min(x)),
                ('skew_S2','skew')],
              'S3' : [('mean_S3','mean'),
                ('std_S3','std'),
                ('med_S3','median'),
                ('max_S3','max'),
                ('min_S3','min'),
                ('range_S3',lambda x: max(x) - min(x)),
                ('skew_S3','skew')],
               'LAP_NUMBER': [('Total_Lap_Num','max')],
               'PIT_TIME': [('PIT_TIME_cnt','count')],
               'CROSSING_FINISH_LINE_IN_PIT': [('cnt_CROSSING_FINISH_LINE_IN_PIT','count')],
              }

df_test['match_key'] = df_test['DRIVER_NAME'] + df_test['location'] + df_test['match_type'] + df_test['match_name'] 
dftest = df_test.groupby(['match_key','DRIVER_NAME','location','match_name','match_type','TEAM'], as_index=True).agg(aggregation).reset_index()
dftest.columns = dftest.columns.droplevel()
column_names = dftest.columns.values
column_names[:6] = ['match_key','DRIVER_NAME','location','match_name','match_type',  'TEAM']
dftest.columns = column_names
dftest = dftest.drop(columns = ['match_key'])
dftest = dftest.fillna(0)
#df.to_csv('./cleaned/race_final_processed.csv',index = False) #this contains test + train

In [179]:
dftest.shape

(20, 36)

In [180]:
dftest.head()

,DRIVER_NAME,location,match_name,match_type,TEAM,mean_KPH,std_KPH,med_KPH,max_KPH,min_KPH,range_KPH,skew_KPH,mean_S1,std_S1,med_S1,max_S1,min_S1,range_S1,skew_S1,mean_S2,std_S2,med_S2,max_S2,min_S2,range_S2,skew_S2,mean_S3,std_S3,med_S3,max_S3,min_S3,range_S3,skew_S3,Total_Lap_Num,PIT_TIME_cnt,cnt_CROSSING_FINISH_LINE_IN_PIT
0,Adam CARROLL,Bejing,Non Qualifying Practice 1,FP1,Panasonic Jaguar Racing,104.580000,19.621894,110.90,115.0,12.9,102.1,-3.663720,23426.142857,6209.532819,21886.0,57955.0,20995.0,36960.0,5.362344,18941.942857,2866.137224,18016.0,34004.0,17339.0,16665.0,4.564494,30231.457143,69899.175756,17045.0,430097.0,16723.0,413374.0,5.834986,35.0,35,1
1,Antonio Felix DA COSTA,Bejing,Non Qualifying Practice 1,FP1,Andretti Formula E,104.794118,22.345699,111.85,115.7,17.8,97.9,-3.540209,23398.764706,6971.638680,21737.5,61461.0,20848.0,40613.0,5.251934,18535.352941,1391.767873,18002.5,23648.0,17303.0,6345.0,2.242252,31761.441176,60311.627846,17034.5,315195.0,16668.0,298527.0,4.204528,34.0,34,2
2,Daniel ABT,Bejing,Non Qualifying Practice 1,FP1,ABT Schaeffler Audi Sport,103.500000,20.168065,110.80,115.8,15.5,100.3,-2.969376,22803.166667,3919.760477,21461.5,42287.0,20790.0,21497.0,3.875134,18726.416667,1836.751626,18123.0,26915.0,17374.0,9541.0,2.928487,29435.388889,58705.574843,17084.0,367730.0,16558.0,351172.0,5.786944,36.0,36,3
3,Esteban GUTIERREZ,Bejing,Non Qualifying Practice 1,FP1,TECHEETAH,100.489286,29.182343,112.05,117.3,12.1,105.2,-2.378624,26423.035714,18156.410849,21361.0,114899.0,20639.0,94260.0,4.672580,18214.321429,1311.299414,17661.5,21880.0,17058.0,4822.0,1.722844,46164.321429,107622.936014,17056.5,486103.0,16474.0,469629.0,3.676940,28.0,28,2
4,Felix ROSENQVIST,Bejing,Non Qualifying Practice 1,FP1,Mahindra Racing,104.763889,20.297588,113.10,117.7,16.8,100.9,-3.034879,23644.166667,6784.789697,21523.0,59193.0,20396.0,38797.0,4.507064,18479.194444,1799.567532,17528.0,23130.0,16886.0,6244.0,1.466451,27422.916667,54273.555107,16969.0,340895.0,16459.0,324436.0,5.830133,36.0,36,2

In [187]:
df_test.DRIVER_NAME.unique()

array(['Lucas DI GRASSI', 'Felix ROSENQVIST', 'Sam BIRD', 'Mitch EVANS',
       'Nick HEIDFELD', 'Jean-Eric VERGNE', 'Robin FRIJNS',
       'Antonio Felix DA COSTA', 'Nelson PIQUET JR', 'Esteban GUTIERREZ',
       'JosÃ© Maria LOPEZ', 'StÃ©phane SARRAZIN', 'Adam CARROLL',
       'Maro ENGEL', 'LoÃ¯c DUVAL', 'Daniel ABT', "JÃ©rÃ´me D'AMBROSIO",
       'Nicolas PROST', 'Oliver TURVEY', 'SÃ©bastien BUEMI',
       'Jarno Trulli', 'Lucas di Grassi', 'Michela Cerruti', 'Sam Bird',
       'Bruno Senna', 'Nick Heidfeld', 'Franck Montagny', 'Charles Pic',
       'Jaime Alguersuari', 'Stephane Sarrazin', 'Karun Chandhok',
       'Takuma Sato', 'Oriol Servia', 'Daniel Abt',
       "JÃ©rome d'AmbrosioÂ\xa0", 'Katherine Legge', 'Nicolas Prost',
       'Ho-Pin Tung', 'Sebastien Buemi', 'Nelson Piquet JR'], dtype=object)

In [188]:
df_test.head()

,PIT_TIME,LAP_NUMBER,KPH,CROSSING_FINISH_LINE_IN_PIT,S1,S2,S3,TEAM,DRIVER_NAME,location,match_type,match_name,match_key
0,12256.0,1.0,80.5,NaN,40055.0,20461.0,18419.0,ABT Schaeffler Audi Sport,Lucas DI GRASSI,Bejing,FP1,Non Qualifying Practice 1,Lucas DI GRASSIBejingFP1Non Qualifying Practice 1
1,0.0,2.0,104.0,NaN,23287.0,19299.0,18493.0,ABT Schaeffler Audi Sport,Lucas DI GRASSI,Bejing,FP1,Non Qualifying Practice 1,Lucas DI GRASSIBejingFP1Non Qualifying Practice 1
2,0.0,3.0,111.8,NaN,21710.0,18042.0,17062.0,ABT Schaeffler Audi Sport,Lucas DI GRASSI,Bejing,FP1,Non Qualifying Practice 1,Lucas DI GRASSIBejingFP1Non Qualifying Practice 1
3,0.0,4.0,41.3,B,21740.0,18370.0,113627.0,ABT Schaeffler Audi Sport,Lucas DI GRASSI,Bejing,FP1,Non Qualifying Practice 1,Lucas DI GRASSIBejingFP1Non Qualifying Practice 1
4,106166.0,5.0,103.8,NaN,25355.0,18688.0,17200.0,ABT Schaeffler Audi Sport,Lucas DI GRASSI,Bejing,FP1,Non Qualifying Practice 1,Lucas DI GRASSIBejingFP1Non Qualifying Practice 1

In [87]:
dftest.head()

Empty DataFrame
Columns: [DRIVER_NAME, location, season_year, match_name, match_type, GROUP, TEAM, mean_KPH, std_KPH, med_KPH, max_KPH, min_KPH, range_KPH, skew_KPH, mean_S1, std_S1, med_S1, max_S1, min_S1, range_S1, skew_S1, mean_S2, std_S2, med_S2, max_S2, min_S2, range_S2, skew_S2, mean_S3, std_S3, med_S3, max_S3, min_S3, range_S3, skew_S3, Total_Lap_Num, PIT_TIME_cnt, cnt_CROSSING_FINISH_LINE_IN_PIT]
Index: []

In [70]:
df.head()

,DRIVER_NAME,location,season_year,match_name,match_type,GROUP,TEAM,mean_KPH,std_KPH,med_KPH,max_KPH,min_KPH,range_KPH,skew_KPH,mean_S1,std_S1,med_S1,max_S1,min_S1,range_S1,skew_S1,mean_S2,std_S2,med_S2,max_S2,min_S2,range_S2,skew_S2,mean_S3,std_S3,med_S3,max_S3,min_S3,range_S3,skew_S3,Total_Lap_Num,PIT_TIME_cnt,cnt_CROSSING_FINISH_LINE_IN_PIT
0,MA Qing Hua,Buenos,2016-2017,Groups Qualifying Session,Q,4,TECHEETAH,55.950000,74.034080,55.95,108.3,3.6,104.7,0.000000,1.205626e+06,1.673677e+06,1205626.5,2389095.0,22158.0,2366937.0,0.000000,28569.500000,2348.301620,28569.5,30230.0,26909.0,3321.0,0.000000,33244.500000,132.228968,33244.5,33338.0,33151.0,187.0,0.000000,2.0,2,0
1,MA Qing Hua,HongKong,2016-2017,Groups Qualifying Session,Q,2,TECHEETAH,60.720000,44.706677,83.70,103.4,9.6,93.8,-0.504993,1.454818e+05,2.776263e+05,21419.0,642077.0,18214.0,623863.0,2.235218,25340.400000,3472.268898,25310.0,30446.0,20834.0,9612.0,0.398980,100467.400000,163235.989761,27764.0,392459.0,25098.0,367361.0,2.235539,5.0,5,1
2,MA Qing Hua,HongKong,2016-2017,Race,Race,2,TECHEETAH,19.200000,0.000000,19.20,19.2,19.2,0.0,0.000000,2.520100e+04,0.000000e+00,25201.0,25201.0,25201.0,0.0,0.000000,69831.000000,0.000000,69831.0,69831.0,69831.0,0.0,0.000000,254614.000000,0.000000,254614.0,254614.0,254614.0,0.0,0.000000,1.0,1,1
3,MA Qing Hua,Marrakesh,2016-2017,Groups Qualifying Session,Q,1,TECHEETAH,96.700000,21.620515,89.10,128.5,80.1,48.4,1.761566,3.075050e+04,2.285297e+04,34467.5,54067.0,0.0,54067.0,-0.879319,32754.500000,22510.967172,40873.0,49272.0,0.0,49272.0,-1.666986,17328.750000,12946.936198,19069.5,31176.0,0.0,31176.0,-0.771944,4.0,4,2
4,MA Qing Hua,Newyork2,2017-2018,Qualifying 2 Group 1,Q,1,NIO Formula E Team,74.933333,36.874698,93.10,99.2,32.5,66.7,-1.678880,5.431333e+04,3.739482e+04,33244.0,97489.0,32207.0,65282.0,1.730552,28552.333333,1275.374585,29261.0,29316.0,27080.0,2236.0,-1.728428,27890.333333,1207.169140,27685.0,29187.0,26799.0,2388.0,0.743282,3.0,3,0

#### Run script from this checkpoint

In [9]:
dr = pd.read_csv('./cleaned/race_final_processed.csv')
dw = pd.read_csv('./cleaned/weather_processed.csv')
final_data = dr.merge(dw, how = 'left', on = ['location','season_year','match_name','match_type'])
final_data_with_weather = final_data[final_data['mean_air_temp'].notnull()]
final_data_with_weather.shape, dr.shape

((664, 74), (1908, 38))

In [10]:
test_data = pd.read_csv('')

FileNotFoundError: [Errno 2] File  does not exist: ''

In [11]:
dr.head(20)

,DRIVER_NAME,location,season_year,match_name,match_type,GROUP,TEAM,mean_KPH,std_KPH,med_KPH,max_KPH,min_KPH,range_KPH,skew_KPH,mean_S1,std_S1,med_S1,max_S1,min_S1,range_S1,skew_S1,mean_S2,std_S2,med_S2,max_S2,min_S2,range_S2,skew_S2,mean_S3,std_S3,med_S3,max_S3,min_S3,range_S3,skew_S3,Total_Lap_Num,PIT_TIME_cnt,cnt_CROSSING_FINISH_LINE_IN_PIT
0,MA Qing Hua,Buenos,2016-2017,Groups Qualifying Session,Q,4.0,TECHEETAH,55.950000,74.034080,55.95,108.3,3.6,104.7,0.000000,1.205626e+06,1.673677e+06,1205626.5,2389095.0,22158.0,2366937.0,0.000000,28569.500000,2348.301620,28569.5,30230.0,26909.0,3321.0,0.000000,33244.500000,132.228968,33244.5,33338.0,33151.0,187.0,0.000000,2.0,2,0
1,MA Qing Hua,HongKong,2016-2017,Groups Qualifying Session,Q,2.0,TECHEETAH,60.720000,44.706677,83.70,103.4,9.6,93.8,-0.504993,1.454818e+05,2.776263e+05,21419.0,642077.0,18214.0,623863.0,2.235218,25340.400000,3472.268898,25310.0,30446.0,20834.0,9612.0,0.398980,100467.400000,163235.989761,27764.0,392459.0,25098.0,367361.0,2.235539,5.0,5,1
2,MA Qing Hua,HongKong,2016-2017,Race,Race,2.0,TECHEETAH,19.200000,0.000000,19.20,19.2,19.2,0.0,0.000000,2.520100e+04,0.000000e+00,25201.0,25201.0,25201.0,0.0,0.000000,69831.000000,0.000000,69831.0,69831.0,69831.0,0.0,0.000000,254614.000000,0.000000,254614.0,254614.0,254614.0,0.0,0.000000,1.0,1,1
3,MA Qing Hua,Marrakesh,2016-2017,Groups Qualifying Session,Q,1.0,TECHEETAH,96.700000,21.620515,89.10,128.5,80.1,48.4,1.761566,3.075050e+04,2.285297e+04,34467.5,54067.0,0.0,54067.0,-0.879319,32754.500000,22510.967172,40873.0,49272.0,0.0,49272.0,-1.666986,17328.750000,12946.936198,19069.5,31176.0,0.0,31176.0,-0.771944,4.0,4,2
4,MA Qing Hua,Newyork2,2017-2018,Qualifying 2 Group 1,Q,1.0,NIO Formula E Team,74.933333,36.874698,93.10,99.2,32.5,66.7,-1.678880,5.431333e+04,3.739482e+04,33244.0,97489.0,32207.0,65282.0,1.730552,28552.333333,1275.374585,29261.0,29316.0,27080.0,2236.0,-1.728428,27890.333333,1207.169140,27685.0,29187.0,26799.0,2388.0,0.743282,3.0,3,0
5,MA Qing Hua,Paris,2017-2018,Qualifying Group 4,Q,4.0,NIO Formula E Team,82.633333,33.691146,93.30,109.7,44.9,64.8,-1.281899,3.527567e+04,2.974910e+04,19071.0,69609.0,17147.0,52462.0,1.723904,27218.666667,2207.172928,27469.0,29290.0,24897.0,4393.0,-0.503816,24313.666667,3295.023874,24447.0,27540.0,20954.0,6586.0,-0.181795,3.0,3,0
6,Adam CARROLL,Berlin2,2016-2017,Qualifying 2 Group 2,Q,2.0,Panasonic Jaguar Racing,99.300000,27.834511,112.70,117.9,67.3,50.6,-1.664292,4.244933e+04,2.746770e+04,27296.0,74156.0,25896.0,48260.0,1.726990,21094.000000,1234.229719,21143.0,22303.0,19836.0,2467.0,-0.178372,24472.333333,785.105301,24266.0,25340.0,23811.0,1529.0,1.100960,3.0,3,0
7,Adam CARROLL,Berlin,2016-2017,Qualifying 1 Group 1,Q,1.0,Panasonic Jaguar Racing,88.533333,44.979366,111.60,117.3,36.7,80.6,-1.700811,7.593933e+04,8.511713e+04,27359.0,174222.0,26237.0,147985.0,1.731712,21477.333333,1526.940187,21435.0,23025.0,19972.0,3053.0,0.124663,24800.666667,1195.927395,24647.0,26066.0,23689.0,2377.0,0.568666,3.0,3,0
8,Adam CARROLL,Buenos,2016-2017,Groups Qualifying Session,Q,1.0,Panasonic Jaguar Racing,83.425000,50.222331,94.50,125.8,18.9,106.9,-0.760870,3.208000e+04,2.420781e+04,20963.0,68217.0,18177.0,50040.0,1.943913,26926.750000,3281.335742,26062.5,31419.0,24163.0,7256.0,1.141666,127973.250000,193163.185955,32798.0,417691.0,28606.0,389085.0,1.998883,4.0,4,1
9,Adam CARROLL,HongKong,2016-2017,Groups Qualifying Session,Q,1.0,Panasonic Jaguar Racing,86.733333,25.444908,98.80,103.9,57.5,46.4,-1.654099,3.464500e+04,2.677151e+04,19765.0,65551.0,18619.0,46932.0,1.728481,22133.666667,1741.631515,21878.0,23989.0,20534.0,3455.0,0.646352,26092.333333,786.995129,26157.0,26845.0,25275.0,1570.0,-0.367264,3.0,3,0
10,Adam CARROLL,HongKong,2016-2017,Race,Race,1.0,Panasonic Jaguar Racing,96.331111,13.880674,101.70,103.4,47.6,55.8,-2.738588,2.052049e+04,5.079578e+03,19018.0,47245.0,18671.0,28574.0,4.172284,23287.444444,6543.679270,21397.0,55010.0,20879.0,34131.0,3.978093,28128.444444,8830.058274,25503.0,72797.0,25021.0,47776.0,3.995479,45.0,45,1
11,Adam CARROLL,Marrakesh,2016-2017,Groups Qualifying Session,Q,4.0,Panasonic Jaguar Racing,84.866667,68.734004,124.30,124.8,5.5,119.3,-1.731948,6.509710e+05,1.073073e+06,32234.0,1890049.0,30630.0,1859419.0,1.732046,38118.666667,2030.262134,37573.0,40366.0,36417.0,3949.0,1.122085,18233.333333,1352.139539,17492.0,19794.0,17414.0,2380.0,1.725569,3.0,3,0
12,Adam CARROLL,Mexico,2016-2017,Groups Qualifying Session,Q,4.0,Panasonic Jaguar Racing,74.666667,62.353535,102.10,118.6,3.3,115.3,-1.596605,7.580753e+05,1.284200e+06,18317.0,2240941.0,14968.0,2225973.0,1.732038,31229.000000,2173.630143,30993.0,33511.0,29183.0,4328.0,0.482824,22042.000000,2540.206488,22255.0,24469.0,19402.0,5067.0,-0.374678,3.0,3,0
13,Adam CARROLL,Monaco,2016-2017,Qualifying Group 2,Q,2.0,Panasonic Jaguar Racing,96.100000,24.769134,104.60,115.5,68.2,47.3,-1.362401,3.317933e+04,1.850597e+04,24316.0,54450.0,20772.0,33678.0,1.660862,19260.333333,1566.478960,19806.0,20481.0,17494.0,2987.0,-1.377324,17196.666667,874.438296,16765.0,18203.0,16622.0,1581.0,1.680086,3.0,3,0
14,Adam CARROLL,Montreal2,2016-2017,Qualifying 2 Group 1,Q,1.0,Panasonic Jaguar Racing,89.233333,40.779938,107.60,117.6,42.5,75.1,-1.615616,7.596467e+04,8.155108e+04,29997.0,170123.0,27774.0,142349.0,1.730603,31670.000000,2007.987301,32079.0,33442.0,29489.0,3953.0,-0.878562,28521.000000,1562.983045,29055.0,29747.0,26761.0,2986.0,-1.357982,3.0,3,0
15,Adam CARROLL,Montreal,2016-2017,Qualifying 1 Group 4,Q,4.0,Panasonic Jaguar Racing,88.933333,39.746363,105.40,117.8,43.6,74.2,-1.544331,7.252100e+04,7.431699e+04,31522.0,158307.0,27734.0,130573.0,1.726990,32873.333333,3307.993702,33205.0,36003.0,29412.0,6591.0,-0.446644,29401.333333,2864.881208,29059.0,32422.0,26723.0,5699.0,0.530041,3.0,3,0
16,Adam CARROLL,Montreal,2016-2017,Race 1,Race,4.0,Panasonic Jaguar Racing,105.162857,18.847532,113.40,115.7,49.2,66.5,-2.141420,3.276471e+04,1.116206e+04,28912.0,75600.0,28150.0,47450.0,2.998900,33488.114286,9224.461638,30350.0,64116.0,29777.0,34339.0,2.914870,32753.000000,12995.136733,27840.0,81278.0,27460.0,53818.0,2.656275,35.0,35,1
17,Adam CARROLL,Newyork,2016-2017,Qualifying 1 Group 3,Q,3.0,Panasonic Jaguar Racing,94.800000,19.936900,101.40,110.6,72.4,38.2,-1.326443,3.490400e+04,1.444645e+04,28245.0,51479.0,24988.0,26491.0,1.633533,19609.000000,1626.601672,19630.0,21225.0,17972.0,3253.0,-0.058087,22176.333333,2014.197193,21490.0,24444.0,20595.0,3849.0,1.355328,3.0,3,0
18,Adam CARROLL,Newyork,2016-2017,Race 1,Race,3.0,Panasonic Jaguar Racing,99.632558,15.839098,106.00,107.7,48.4,59.3,-2.431678,2.882186e+04,8.789371e+03,26301.0,73022.0,25766.0,47256.0,4.048364,19822.093023,4339.543924,18471.0,39514.0,18229.0,21285.0,3.689249,24875.767442,10963.254778,21615.0,70499.0,21218.0,49281.0,3.642128,43.0,43,1
19,Adam CARROLL,Paris,2016-2017,Qualifying Group 4,Q,4.0,Panasonic Jaguar Racing,87.766667,28.459152,99.60,108.4,55.3,53.1,-1.547608,3.675300e+04,3.213452e+04,19144.0,73843.0,17272.0,56571.0,1.725440,26739.000000,1311.934450,27451.0,27541.0,25225.0,2316.0,-1.722885,22564.333333,1210.541339,22744.0,23675.0,21274.0,2401.0,-0.653171,3.0,3,0

In [12]:
from sklearn.preprocessing import OneHotEncoder

def encode_column_to_dataframe(df, allcols):
    '''Takes the column name as a string and adds to the dataframe'''
    for col in allcols:
        #dum_df = pd.get_dummies(df, columns=col, prefix=col)
        # creating instance of one-hot-encoder
        enc = OneHotEncoder(handle_unknown='ignore')
        # passing bridge-types-cat column (label encoded values of bridge_types)
        enc_df = pd.DataFrame(enc.fit_transform(df[[col]]).toarray())
        # merge with main df bridge_df on key values
        df = df.join(enc_df.add_prefix(col+"_"))
    return df

In [13]:
def get_encoded_dataframe(final):
    final_data = encode_column_to_dataframe(final,['DRIVER_NAME','location','season_year', 'match_name','match_type','GROUP', 'TEAM'])
    final_data.drop(columns = ['DRIVER_NAME','location','season_year', 'match_name','match_type','GROUP', 'TEAM'],inplace = True)
    #final_copy.to_csv('./cleaned/final_processed_before_ml.csv')
    #drop only if that column exists originally
    #final_data.drop(columns = ['Unnamed: 0'],inplace = True)
    return final_data

#### *Without Weather Model Running*

In [14]:
#Generating model-ready data using one hot encoding

final_df = get_encoded_dataframe(dr)
y = final_df['Total_Lap_Num'].to_numpy()
X = final_df.drop(columns = ['Total_Lap_Num']).to_numpy()

In [15]:
from sklearn import ensemble, linear_model, neighbors, svm
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

In [16]:
def test_model(X, y, model_name, model):
    print("MODEL: {}".format(model_name))
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
    model.fit(X_train, y_train)
    Z = model.predict(X_test)
    print("R2 Value: ", r2_score(Z, y_test))
    print("MSE Value: ", mean_squared_error(Z, y_test))
    
models = {
    #"RANSACRegressor": linear_model.RANSACRegressor(random_state=0),
    "ElasticNet": linear_model.ElasticNet(random_state=0),
    "Random Forest": ensemble.RandomForestRegressor(n_estimators=1000),
    "K-Nearest Neighbors": neighbors.KNeighborsRegressor(),
    "SVR": svm.SVR(),
    "BayesianRidge": linear_model.BayesianRidge()
}

In [18]:
for model in models.keys():
    print('----------------------\n')
    test_model(X,y,model, models[model])

----------------------

MODEL: ElasticNet

/opt/miniconda3/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 930.7062825607859, tolerance: 29.733034403669723
  model = cd_fast.enet_coordinate_descent(

R2 Value:  0.9999206674201226
MSE Value:  0.014293738325552108
----------------------

MODEL: Random Forest
R2 Value:  0.9999907929344992
MSE Value:  0.001701358638743446
----------------------

MODEL: K-Nearest Neighbors
R2 Value:  0.9192846930962785
MSE Value:  14.417172774869112
----------------------

MODEL: SVR
R2 Value:  -10.093056578453377
MSE Value:  247.81198120483305
----------------------

MODEL: BayesianRidge
R2 Value:  0.9999992275587556
MSE Value:  0.0001527409169916069

#### *With Weather Model Running*

In [19]:
final_data_with_weather.head()

,DRIVER_NAME,location,season_year,match_name,match_type,GROUP,TEAM,mean_KPH,std_KPH,med_KPH,max_KPH,min_KPH,range_KPH,skew_KPH,mean_S1,std_S1,med_S1,max_S1,min_S1,range_S1,skew_S1,mean_S2,std_S2,med_S2,max_S2,min_S2,range_S2,skew_S2,mean_S3,std_S3,med_S3,max_S3,min_S3,range_S3,skew_S3,Total_Lap_Num,PIT_TIME_cnt,cnt_CROSSING_FINISH_LINE_IN_PIT,DATE_ONLY,mean_air_temp,std_air_temp,med_air_temp,max_air_temp,min_air_temp,range_air_temp,skew_air_temp,mean_track_temp,std_track_temp,med_track_temp,max_track_temp,min_track_temp,range_track_temp,skew_track_temp,mean_HUMIDITY,std_HUMIDITY,med_HUMIDITY,max_HUMIDITY,min_HUMIDITY,range_HUMIDITY,skew_HUMIDITY,mean_PRESSURE,std_PRESSURE,med_PRESSURE,max_PRESSURE,min_PRESSURE,range_PRESSURE,skew_PRESSURE,mean_WIND_SPEED,std_WIND_SPEED,med_WIND_SPEED,max_WIND_SPEED,min_WIND_SPEED,range_WIND_SPEED,skew_WIND_SPEED
0,MA Qing Hua,Buenos,2016-2017,Groups Qualifying Session,Q,4.0,TECHEETAH,55.950000,74.034080,55.95,108.3,3.6,104.7,0.000000,1.205626e+06,1.673677e+06,1205626.5,2389095.0,22158.0,2366937.0,0.000000,28569.500000,2348.301620,28569.5,30230.0,26909.0,3321.0,0.000000,33244.500000,132.228968,33244.5,33338.0,33151.0,187.0,0.000000,2.0,2,0,02/18/2017,26.299227,0.067998,26.2778,26.4444,26.2222,0.2222,0.634238,26.250000,0.243363,26.1111,26.6667,26.1111,0.5556,1.195861,74.931818,0.899554,75.0,76.0,73.0,3.0,-0.665006,1008.236136,0.126201,1008.230,1008.470,1008.030,0.440,0.053279,4.462272,2.049350,4.828030,8.04672,0.00000,8.04672,0.095071
1,MA Qing Hua,HongKong,2016-2017,Groups Qualifying Session,Q,2.0,TECHEETAH,60.720000,44.706677,83.70,103.4,9.6,93.8,-0.504993,1.454818e+05,2.776263e+05,21419.0,642077.0,18214.0,623863.0,2.235218,25340.400000,3472.268898,25310.0,30446.0,20834.0,9612.0,0.398980,100467.400000,163235.989761,27764.0,392459.0,25098.0,367361.0,2.235539,5.0,5,1,09/10/2016,29.942807,0.313382,29.9444,30.7222,29.5000,1.2222,1.002514,40.833341,0.839526,40.5556,42.2222,40.0000,2.2222,0.454498,67.808824,0.758186,68.0,69.0,66.0,3.0,-0.932719,1007.657794,0.230657,1007.720,1007.930,1007.250,0.680,-0.483309,3.526356,1.870559,3.218690,8.04672,0.00000,8.04672,0.260616
3,MA Qing Hua,Marrakesh,2016-2017,Groups Qualifying Session,Q,1.0,TECHEETAH,96.700000,21.620515,89.10,128.5,80.1,48.4,1.761566,3.075050e+04,2.285297e+04,34467.5,54067.0,0.0,54067.0,-0.879319,32754.500000,22510.967172,40873.0,49272.0,0.0,49272.0,-1.666986,17328.750000,12946.936198,19069.5,31176.0,0.0,31176.0,-0.771944,4.0,4,2,12/11/2016,19.256183,0.185109,19.2778,19.5556,18.7778,0.7778,-0.816759,22.608022,1.027137,22.7778,23.8889,20.5556,3.3333,-0.269498,65.138889,0.960737,65.0,68.0,64.0,4.0,0.936207,962.197528,0.152585,962.246,962.415,961.907,0.508,-0.495600,5.096257,2.324215,4.828030,9.65606,0.00000,9.65606,-0.247735
4,MA Qing Hua,Newyork2,2017-2018,Qualifying 2 Group 1,Q,1.0,NIO Formula E Team,74.933333,36.874698,93.10,99.2,32.5,66.7,-1.678880,5.431333e+04,3.739482e+04,33244.0,97489.0,32207.0,65282.0,1.730552,28552.333333,1275.374585,29261.0,29316.0,27080.0,2236.0,-1.728428,27890.333333,1207.169140,27685.0,29187.0,26799.0,2388.0,0.743282,3.0,3,0,07/15/2018,22.518533,0.045397,22.5278,22.5556,22.4444,0.1112,-0.857321,23.333300,0.000000,23.3333,23.3333,23.3333,0.0000,0.000000,89.333333,0.516398,89.0,90.0,89.0,1.0,0.968246,1015.210000,0.000000,1015.210,1015.210,1015.210,0.000,0.000000,3.005982,1.043103,2.652335,4.24374,2.12187,2.12187,0.455943
5,MA Qing Hua,Paris,2017-2018,Qualifying Group 4,Q,4.0,NIO Formula E Team,82.633333,33.691146,93.30,109.7,44.9,64.8,-1.281899,3.527567e+04,2.974910e+04,19071.0,69609.0,17147.0,52462.0,1.723904,27218.666667,2207.172928,27469.0,29290.0,24897.0,4393.0,-0.503816,24313.666667,3295.023874,24447.0,27540.0,20954.0,6586.0,-0.181795,3.0,3,0,04/28/2018,15.333333,0.049685,15.3333,15.3889,15.2778,0.1111,0.001509,21.666700,0.000000,21.6667,21.6667,21.6667,0.0000,0.000000,59.833333,0.408248,60.0,60.0,59.0,1.0,-2.449490,1007.153333,0.025820,1007.150,1007.180,1007.110,0.070,-0.759105,1.768222,0.866251,1.591400,3.18280,1.06093,2.12187,0.857312

In [20]:
final_df = get_encoded_dataframe(final_data_with_weather)
final_df = final_df.fillna(0)
y = final_df['Total_Lap_Num'].to_numpy()
X = final_df.drop(columns = ['Total_Lap_Num','DATE_ONLY']).to_numpy()

In [21]:
final_df.head()

,mean_KPH,std_KPH,med_KPH,max_KPH,min_KPH,range_KPH,skew_KPH,mean_S1,std_S1,med_S1,max_S1,min_S1,range_S1,skew_S1,mean_S2,std_S2,med_S2,max_S2,min_S2,range_S2,skew_S2,mean_S3,std_S3,med_S3,max_S3,min_S3,range_S3,skew_S3,Total_Lap_Num,PIT_TIME_cnt,cnt_CROSSING_FINISH_LINE_IN_PIT,DATE_ONLY,mean_air_temp,std_air_temp,med_air_temp,max_air_temp,min_air_temp,range_air_temp,skew_air_temp,mean_track_temp,std_track_temp,med_track_temp,max_track_temp,min_track_temp,range_track_temp,skew_track_temp,mean_HUMIDITY,std_HUMIDITY,med_HUMIDITY,max_HUMIDITY,min_HUMIDITY,range_HUMIDITY,skew_HUMIDITY,mean_PRESSURE,std_PRESSURE,med_PRESSURE,max_PRESSURE,min_PRESSURE,range_PRESSURE,skew_PRESSURE,mean_WIND_SPEED,std_WIND_SPEED,med_WIND_SPEED,max_WIND_SPEED,min_WIND_SPEED,range_WIND_SPEED,skew_WIND_SPEED,DRIVER_NAME_0,DRIVER_NAME_1,DRIVER_NAME_2,DRIVER_NAME_3,DRIVER_NAME_4,DRIVER_NAME_5,DRIVER_NAME_6,DRIVER_NAME_7,DRIVER_NAME_8,DRIVER_NAME_9,DRIVER_NAME_10,DRIVER_NAME_11,DRIVER_NAME_12,DRIVER_NAME_13,DRIVER_NAME_14,DRIVER_NAME_15,DRIVER_NAME_16,DRIVER_NAME_17,DRIVER_NAME_18,DRIVER_NAME_19,DRIVER_NAME_20,DRIVER_NAME_21,DRIVER_NAME_22,DRIVER_NAME_23,DRIVER_NAME_24,DRIVER_NAME_25,DRIVER_NAME_26,DRIVER_NAME_27,DRIVER_NAME_28,DRIVER_NAME_29,DRIVER_NAME_30,DRIVER_NAME_31,DRIVER_NAME_32,DRIVER_NAME_33,DRIVER_NAME_34,DRIVER_NAME_35,DRIVER_NAME_36,DRIVER_NAME_37,DRIVER_NAME_38,DRIVER_NAME_39,DRIVER_NAME_40,DRIVER_NAME_41,DRIVER_NAME_42,DRIVER_NAME_43,DRIVER_NAME_44,DRIVER_NAME_45,DRIVER_NAME_46,DRIVER_NAME_47,DRIVER_NAME_48,DRIVER_NAME_49,location_0,location_1,location_2,location_3,location_4,location_5,location_6,location_7,location_8,location_9,location_10,location_11,location_12,location_13,location_14,location_15,location_16,location_17,location_18,location_19,season_year_0,season_year_1,match_name_0,match_name_1,match_name_2,match_name_3,match_name_4,match_name_5,match_name_6,match_name_7,match_name_8,match_name_9,match_name_10,match_name_11,match_name_12,match_name_13,match_name_14,match_name_15,match_name_16,match_name_17,match_name_18,match_name_19,match_name_20,match_type_0,match_type_1,match_type_2,GROUP_0,GROUP_1,GROUP_2,GROUP_3,TEAM_0,TEAM_1,TEAM_2,TEAM_3,TEAM_4,TEAM_5,TEAM_6,TEAM_7,TEAM_8,TEAM_9,TEAM_10,TEAM_11,TEAM_12
0,55.950000,74.034080,55.95,108.3,3.6,104.7,0.000000,1.205626e+06,1.673677e+06,1205626.5,2389095.0,22158.0,2366937.0,0.000000,28569.500000,2348.301620,28569.5,30230.0,26909.0,3321.0,0.000000,33244.500000,132.228968,33244.5,33338.0,33151.0,187.0,0.000000,2.0,2,0,02/18/2017,26.299227,0.067998,26.2778,26.4444,26.2222,0.2222,0.634238,26.250000,0.243363,26.1111,26.6667,26.1111,0.5556,1.195861,74.931818,0.899554,75.0,76.0,73.0,3.0,-0.665006,1008.236136,0.126201,1008.230,1008.470,1008.030,0.440,0.053279,4.462272,2.049350,4.828030,8.04672,0.00000,8.04672,0.095071,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,60.720000,44.706677,83.70,103.4,9.6,93.8,-0.504993,1.454818e+05,2.776263e+05,21419.0,642077.0,18214.0,623863.0,2.235218,25340.400000,3472.268898,25310.0,30446.0,20834.0,9612.0,0.398980,100467.400000,163235.989761,27764.0,392459.0,25098.0,367361.0,2.235539,5.0,5,1,09/10/2016,29.942807,0.313382,29.9444,30.7222,29.5000,1.2222,1.002514,40.833341,0.839526,40.5556,42.2222,40.0000,2.2222,0.454498,67.808824,0.758186,68.0,69.0,66.0,3.0,-0.932719,1007.657794,0.230657,1007.720,1007.930,1007.250,0.680,-0.483309,3.526356,1.870559,3.218690,8.04672,0.00000,8.04672,0.260616,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,96.700000,21.620515,89.10,128.5,80.1,48.4,1.761566,3.075050e+04,2.285297e+04,34467.5,54067.0,0.0,54067.0,-0.879319,32754.500000,22510.967172,40873.0,49272.0,0.0,49272.0,-1.666986,17328.750000,12946.936198,19069.5,31176.0,0.0,31176.0,-0.771944,4.0,4,2,12/11/2016,19.256183,0.185109,19.2778,19.5556,18.7778,0.7778,-0.816759,22.608022,1.027137,22.7778,23.8889,20.5556,3.3333,-0.269498,65.138889,0.960737,65.0,68.0,64.0,4.0,0.936207,962.197528,0.152585,962.246,962.415,961.907,0.508,-0.495600,5.096257,2.324215,4.828030,9.65606,0.00000,9.65606,-0.247735,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,74.933333,36.874698,93.10,99.2,32.5,66.7,-1.678880,5.431333e+04,3.739482e+04,33244.0,97489.0,32207.0,65282.0,1.730552,28552.333333,1275.374585,29261.0,29316.0,27080.0,2236.0,-1.728428,27890.333333,1207.169140,27685.0,29187.0,26799.0,2388.0,0.743282,3.0,3,0,07/15/2018,22.518533,0.045397,22.5278,22.5556,22.4444,0.1112,-0.857321,23.333300,0.000000,23.3333,23.3333,23.3333,0.0000,0.000000,89.333333,0.516398,89.0,90.0,89.0,1.0,0.968246,1015.210000,0.000000,1015.210,1015.210,1015.210,0.000,0.000000,3.005982,1.043103,2.652335,4.24374,2.12187,2.12187,0.455943,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
5,82.633333,33.691146,93.30,109.7,44.9,64.8,-1.281899,3.527567e+04,2.974910e+04,19071.0,69609.0,17147.0,52462.0,1.723904,27218.666667,2207.172928,27469.0,29290.0,24897.0,4393.0,-0.503816,24313.666667,3295.023874,24447.0,27540.0,20954.0,6586.0,-0.181795,3.0,3,0,04/28/2018,15.333333,0.049685,15.3333,15.3889,15.2778,0.1111,0.001509,21.666700,0.000000,21.6667,21.6667,21.6667,0.0000,0.000000,59.833333,0.408248,60.0,60.0,59.0,1.0,-2.449490,1007.153333,0.025820,1007.150,1007.180,1007.110,0.070,-0.759105,1.768222,0.866251,1.591400,3.18280,1.06093,2.12187,0.857312,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

In [22]:
for model in models.keys():
    print('----------------------\n')
    test_model(X,y,model, models[model])

----------------------

MODEL: ElasticNet
R2 Value:  0.9958989033559795
MSE Value:  0.11347609925114065
----------------------

MODEL: Random Forest

/opt/miniconda3/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 343.7877368955902, tolerance: 2.319245574387948
  model = cd_fast.enet_coordinate_descent(

R2 Value:  0.9988670829016324
MSE Value:  0.054956488721804586
----------------------

MODEL: K-Nearest Neighbors
R2 Value:  0.8480539264866148
MSE Value:  5.4631578947368435
----------------------

MODEL: SVR
R2 Value:  0.4913310819004135
MSE Value:  10.064437440629987
----------------------

MODEL: BayesianRidge
R2 Value:  0.9876573223693756
MSE Value:  0.6036410140706955